version: "3.9"
services:
  web:
    build: .
    ports:
      - "7777:7777"
    restart: always
  proxy:
    image: nginx:stable-alpine
    ports:
      - "7000:7000"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    links:
      - web