version: '3.9'
services:
  db:
    image: postgres:15.1-alpine
    ports:
    - 5432:5432
    volumes:
    - ./pg_data:/var/lib/postgresql/data/pg_data
    environment:
      POSTGRES_PASSWORD: s3cr3t
      POSTRGES_DB: dummy
      PGDATA: /var/lib/postgresql/data/pg_data
    restart: always
  web:
    build: .
    ports:
    - 7777:7777
    environment:
      HTTP_PORT: 7777
      DB_URL: jdbc:postgresql://db:5432/dummy
      DB_USER: postgres
      DB_PWD: s3cr3t
    restart: always
    links:
    - db
  proxy:
    image: nginx:stable-alpine
    ports:
    - 7000:7000
    volumes:
    - ./default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    links:
    - web